---
name: Galaxy release

# yamllint disable-line rule:truthy
on:
  release:
    types: ['created']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout git repo'
        uses: actions/checkout@v4

      - name: 'release on galaxy'
        uses: ansible-actions/ansible-galaxy-action@v1.0.0
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
